[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements/**",
    "lms_project/**",
    "railway.toml",
    "Dockerfile",
]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3